<a href="https://colab.research.google.com/github/SecondThread/MachineLearningClass/blob/master/HW4/Homework4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem 1: Square Kernal Convolution with Legal Padding

I have implemented the method conv2d, along with two custom exceptions for when
illegal input is given. The three cases for illegal input, as specified by the
problem are:
  - There are no legal places to put the kernal because the kernal is too big
  - The input matrix isn't square
  - The kernal isn't square

In [0]:
import numpy as np;

class NonsquareShapeError(Exception):
  pass;

class KernalTooBigError(Exception):
  pass;

def conv2d(input_mat, kernal_mat):
  input_shape, kernal_shape = input_mat.shape, kernal_mat.shape;
  if input_shape[0] != input_shape[1]:
    raise NonsquareShapeError("The input matrix isn't square as specified in " +
    "the assignment!");
  if kernal_shape[0] != kernal_shape[1]:
    raise NonsquareShapeError("The kernal matrix isn't square as specified in "+
    "the assignment!");
  if (input_shape[0]<kernal_shape[0]):
    raise KernalTooBigError("The size of the kernal is larger than the size "+
    "of the the input matrix, so the kernal cannot be convolved using "+
    "legal padding!");

  output_size=input_shape[0]-kernal_shape[0]+1;
  ans=np.zeros((output_size, output_size));
  for input_x in range(0, output_size):
    for input_y in range(0, output_size):
      total=0;
      for kernal_x in range(0, kernal_shape[0]):
        for kernal_y in range(0, kernal_shape[0]):
          total+=kernal_mat[kernal_x][kernal_y]*input_mat[input_x+kernal_x][input_y+kernal_y];
      ans[input_x][input_y]=total;
  return ans;

res=conv2d(np.zeros((5, 5)), np.zeros((2, 2)));
print(res);

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##Testing `conv2d`

####Correct shape tests:

In [0]:
res=conv2d(np.zeros((5, 5)), np.zeros((2, 2)));
print(res); #should be 4x4

res=conv2d(np.zeros((5, 5)), np.zeros((5, 5)));
print(res); #should be 1x1

res=conv2d(np.zeros((2, 2)), np.zeros((1, 1)));
print(res); #should be 2x2

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.]]
[[0. 0.]
 [0. 0.]]


####Correctly throwing exceptions tests:

In [0]:
conv2d(np.zeros((5, 2)), np.zeros((1, 1)));

NonsquareShapeError: ignored

In [0]:
conv2d(np.zeros((2, 2)), np.zeros((1, 2)));

NonsquareShapeError: ignored

In [0]:
conv2d(np.zeros((2, 2)), np.zeros((3, 3)));

KernalTooBigError: ignored

####Tests provided in assignment:

In [0]:
# This code was copied from the `test_cases_for_problems_1_2_homework_4.ipynb`
# document that we were provided in this class. I didn't not write this code.
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  # if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #   output_mat = []
  # else:
  #   output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!



KernalTooBigError: ignored

#Problem 2: `maxpooling2d`

I have implemented `maxpooling2d` as specified in the assignment using numpy
arrays. There aren't any cases in which my method wouldn't be able to run,
assuming it is given input that is the correct type. If it is given illegal
input, then it will throw exceptions in the methods I call, as intended.

In [0]:
import numpy as np

class MaxPoolStrideTooSmallError(Exception):
  pass;

def maxpooling2d(input_mat, s):
  if s<1:
    raise MaxPoolStrideTooSmallError("s must be at least 1!");
  n = input_mat.shape[0];
  m = input_mat.shape[1];
  ans = np.zeros((n//s, m//s))
  for x_block in range(ans.shape[0]):
    for y_block in range(ans.shape[1]):
      m = input_mat[x_block*s][y_block*s];
      for x in range(s):
        for y in range(s):
          m = max(m, input_mat[x_block*s + x][y_block*s + y]);
      ans[x_block][y_block] = m;
  return ans;

##Testing `maxpooling2d`

Correct shape tests:


In [0]:
res = maxpooling2d(np.zeros((5, 5)), 2);
print(res); # 2x2

res = maxpooling2d(np.zeros((4, 4)), 2);
print(res); # 2x2

res = maxpooling2d(np.zeros((3, 3)), 2);
print(res); # 1x1

res = maxpooling2d(np.zeros((2, 2)), 2);
print(res); # 1x1

res = maxpooling2d(np.zeros((1, 1)), 2);
print(res); # 0x0

[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
[[0.]]
[[0.]]
[]


####Throwing correct exceptions test

In [0]:
maxpooling2d(np.zeros((5, 5)), 0);

MaxPoolStrideTooSmallError: ignored

####Tests provided in assignment

In [0]:
# This code was copied from the `test_cases_for_problems_1_2_homework_4.ipynb`
# document that we were provided in this class. I didn't not write this code.
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")
    print(expected_mat[i]);

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!


#Problem 3: Adapting a pre-trained nueral net



I created two new notebooks for this, as specified in the assignment. In both examples, I used ResNet50V2 (I chose this because I read about it somewhere and a research team was quite impressed with its performance), with two different classifiers, on per notebook. You can see those here:
- https://colab.research.google.com/drive/1MKxbgjdhakmg0YfyG8JLEtZDXhsm78_0
- https://colab.research.google.com/drive/112Gxmbi4lMY5rERv0kkkPTdwr66-fDBk
